pipeline:
  identifier: Build_dhirajchhawchharia_harnesscd_example_apps_1733666956174
  name: Build harnesscd-example-apps
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: dhirajchhawchharia/harnesscd-example-apps
  stages:
    - stage:
        identifier: build
        name: build test and push
        spec:
          caching:
            enabled: true
            paths: []
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: echo Runnning CI in local
                  timeout: ""
                  type: Run
              - step:
                  type: Test
                  name: run tests with Intelligence
                  identifier: run_tests_with_Intelligence
                  spec:
                    shell: Sh
                    command: echo running test intelligence
                    intelligenceMode: true
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
          buildIntelligence:
            enabled: false
        type: CI
        description: ""
        delegateSelectors:
          - macos-arm64
    - stage:
        name: Run Integration tests
        identifier: Run_tests
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
          caching:
            enabled: true
            paths: []
          buildIntelligence:
            enabled: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo running integration tests stage
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: echo running the tests stage is complete
        delegateSelectors:
          - macos-arm64
